### ISSUE TITLE
Support altitude hold

### ISSUE THREAD

**Issue by bitcraze-issue-importer** [bitcraze/crazyflie-android-client#33]
Support altitude hold functionality and add corresponding button mapping preference entry.

---
- Bitbucket: https://bitbucket.org/bitcraze/crazyflie-android-client/issue/33
- Originally Reported By: [ ](http://bitbucket.org/fredg02)
- Originally Created At: 2013-10-29T02:26:27.190

**Comment by NargiT** [comment]
+1

**Comment by knuckles904** [comment]
Also +1. Doesn't have to be anything fancy. A momentary press button which sets Alt Hold parameter=1 on touch and Alt Hold=0 on release, located somewhere reasonably accessible would be great. Feature could/should be enablable from advanced options. 

Even better would be a custom button which could just feed back into a custom parameter. This would allow slightly more advanced users to link the custom button parameter to the advanced features without having to dig into android or IOS development. 

Side note-this is especially relevant now that we have a few sitaw features which rely on Alt hold button toggling.

**Comment by fredg02** [comment]
Fixed with https://github.com/bitcraze/crazyflie-android-client/commit/0ff428e818d761875a7974d88bdfb615c044f57f. Currently altitude hold is only supported when a game pad and the Crazyradio is used.
