### ISSUE TITLE
Trigger axis thrust

### ISSUE THREAD

**Issue by bitcraze-issue-importer** [bitcraze/crazyflie-android-client#35]
Hi, I use a external gamepad (XBox 360) and when i bind the thrust to the left or right trigger (as i do on the PC client) the Thrust doesn't react when I pull down the trigger.

The trigger works for pitch, roll and yaw but not for thrust.

---------------------------------------
- Bitbucket: https://bitbucket.org/bitcraze/crazyflie-android-client/issue/35
- Originally Reported By: [Vaasref ](http://bitbucket.org/Vaasref)
- Originally Created At: 2014-02-27T02:01:00.440

**Comment by fredg02** [comment]
This has been successfully tested with version [v0.5.2] (https://github.com/bitcraze/crazyflie-android-client/releases/tag/v0.5.2) on a Nexus 5 (Android version 5.1.1). It might even work with earlier versions of the client.

The trigger buttons (L2, R2) of a wired XBox360 controller were detected as separate axes (AXIS_BRAKE, AXIS_GAS) and could therefore be assigned to thrust without a problem.

Please re-open if this is still an issue.
