### ISSUE TITLE
BLE connection on Motorola Moto G has serious delay/lag

### ISSUE THREAD

**Issue by fredg02** [bitcraze/crazyflie-android-client#43]
BLE connection works fine with a Nexus 5, but has serious delay/lag with a Moto G.
Delay/lag is in the range of seconds! Therefore BLE on the Moto G is not useable for controlling the Crazyflie 2.0.
I will try to provide more info soon.

**Comment by edelrabe** [comment]
I faced the same bug on my Moto G

**Comment by ataffanel** [comment]
I added the workaround in preferences and pushed the change. Could you test to see if it fixes the big lag? I can provide an APK if you need.

**Comment by edelrabe** [comment]
@ataffanel, I tested the latest version with checkbox, it solves the latency problem on Moto G.
Great job, thanks!

**Comment by fredg02** [comment]
Successfully tested it.
Thanks @ataffanel
