### ISSUE TITLE
Trim cancelled by deadzone

### ISSUE THREAD

**Issue by ottodog** [bitcraze/crazyflie-android-client#54]
Line 97 of AbstractController has getDeadzone multiplying the entire return of getRoll. 

So if user input is in the deadzone, everything, including trim gets nullified by the zero returned by getDeadzone.

Shouldn't trim be applied at all times? 

Trim is supposed to balance the crazyflie if it drifts right?

**Comment by fredg02** [comment]
Thanks, good find! Yes, trim should be applied all the time to compensate drift.
