### ISSUE TITLE
[Android N] Touch controls do no show up when the app is started for the first time

### ISSUE THREAD

**Issue by fredg02** [bitcraze/crazyflie-android-client#60]
With the Android N preview, the touch controls are not shown during the first start of the application. Once you restart the application or go to settings and back, it works.
Thx to @ataffanel for reporting it.

**Comment by lookfuyao** [comment]
I also encountered this bug。

**Comment by fredg02** [comment]
Fixed with https://github.com/bitcraze/crazyflie-android-client/commit/cda5f37d977cd0c63bfe4de27f127a0667c4ff11
