### ISSUE TITLE
Crazyflie AltHold/Hover button

### ISSUE THREAD

**Issue by miili** [bitcraze/crazyflie-android-client#61]
Hi all,

that feature would be great to have on the Android GUI. Would make flying with the soft-joysticks much more fun!

cheers, Marius

**Comment by fredg02** [comment]
Altitude hold/Hover mode has been implemented in release [v0.6.4](https://github.com/bitcraze/crazyflie-android-client/releases/tag/v0.6.4).
For safety reasons, it is only supported when a game pad is used. Without haptic feedback it's just too easy to accidentally trigger hover mode (on or off) and damage the Crazyflie. So I currently don't see a safe way of having an on-screen button for hover mode. Please re-open, if you have any ideas how this can be implemented.
