### ISSUE TITLE
Radio Link quality

### ISSUE THREAD

**Issue by bitcraze-issue-importer** [bitcraze/crazyflie-android-client#8]
Visual bar graph in the app. Vibration alarm and sound alarm at min level. Voice output like Google speech: "Radio Link quality BAD!"

---
- Bitbucket: https://bitbucket.org/bitcraze/crazyflie-android-client/issue/8
- Originally Reported By: [Sascha Heymann](http://bitbucket.org/sheymann)
- Originally Created At: 2013-07-07T19:59:34.877

**Comment by fredg02** [comment]
Basic link/connection quality indicator has been added and works for both Crazyradio and BLE connections.

There are currently no plans to add the "fancy" features.

**Comment by Masongyi** [comment]
> I always get this warning "Link quality low (0.32000)". How can I improve the link quality?

hey i also have this problem , did you figure it out ?

**Comment by fredg02** [comment]
Can you post a screenshot or explain where exactly you see this warning?
