### ISSUE TITLE
Console

### ISSUE THREAD

**Issue by bitcraze-issue-importer** [bitcraze/crazyflie-android-client#9]
For debug and log.

---
- Bitbucket: https://bitbucket.org/bitcraze/crazyflie-android-client/issue/9
- Originally Reported By: [Sascha Heymann](http://bitbucket.org/sheymann)
- Originally Created At: 2013-07-07T20:00:08.282

**Comment by fredg02** [comment]
Basic console view has been implemented (https://github.com/bitcraze/crazyflie-android-client/commit/13111c03f1aa9548620bdd084d238d41fa6c4539).
